name: pageview_widget_indicator
description:
  A builder widget that will allow you to create custom indicators for your flutter pageViews
version: 0.0.3+4
repository: https://github.com/andersonfds/pageview_widget_indicator

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
